export const defaultFilterData = [
  {
    label: 'Temperature',
    path: 'main.temp',
    value: 20,
    format: '°C',
    min: -15,
    max: 40,
    tolerance: 5,
    checked: true,
    converter: x => x - 272,
  },
  {
    label: 'Humidity',
    path: 'main.humidity',
    value: 25,
    format: '%',
    min: 0,
    max: 100,
    tolerance: 5,
    checked: true,
    converter: x => x,
  },
  {
    label: 'Cloudiness',
    path: 'clouds.all',
    value: 0,
    format: '%',
    min: 0,
    max: 100,
    tolerance: 5,
    checked: true,
    converter: x => x,
  },
  {
    label: 'Rain',
    path: 'rain.3h',
    value: 15,
    format: 'mm',
    min: 0,
    max: 100,
    tolerance: 5,
    checked: true,
    converter: x => x,
  },
];
